// pnpm manual:publish が作るファイル。手で直さない (scripts/manual/publish.ts)。
import type { ManualCatalog } from "./types";

export const MANUAL_CATALOG: ManualCatalog = {
  pdfs: [
    {
      audience: "admin",
      title: "管理者マニュアル",
      href: "/manual/admin/manual.pdf",
    },
    {
      audience: "staff",
      title: "職員マニュアル",
      href: "/manual/staff/manual.pdf",
    },
  ],
  videos: [
    {
      audience: "admin",
      title: "ログインと画面の見方",
      href: "/manual/admin/01.mp4",
      poster: "/manual/admin/01.jpg",
      durationSec: 53,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "勤務表を作って職員に公開する",
      href: "/manual/admin/02.mp4",
      poster: "/manual/admin/02.jpg",
      durationSec: 74,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "労働条件通知書を作る",
      href: "/manual/admin/03.mp4",
      poster: "/manual/admin/03.jpg",
      durationSec: 110,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "労働条件通知書の設定を変える",
      href: "/manual/admin/04.mp4",
      poster: "/manual/admin/04.jpg",
      durationSec: 57,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "研修アンケートを作って配る",
      href: "/manual/admin/05.mp4",
      poster: "/manual/admin/05.jpg",
      durationSec: 93,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "研修アンケートの結果を見る",
      href: "/manual/admin/06.mp4",
      poster: "/manual/admin/06.jpg",
      durationSec: 69,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "シフト希望を確認する",
      href: "/manual/admin/07.mp4",
      poster: "/manual/admin/07.jpg",
      durationSec: 61,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "従業員を登録してログインを発行する",
      href: "/manual/admin/08.mp4",
      poster: "/manual/admin/08.jpg",
      durationSec: 74,
      width: 1280,
      height: 720,
    },
    {
      audience: "admin",
      title: "有給を確認する",
      href: "/manual/admin/09.mp4",
      poster: "/manual/admin/09.jpg",
      durationSec: 50,
      width: 1280,
      height: 720,
    },
    {
      audience: "staff",
      title: "はじめてのログイン",
      href: "/manual/staff/11.mp4",
      poster: "/manual/staff/11.jpg",
      durationSec: 45,
      width: 390,
      height: 780,
    },
    {
      audience: "staff",
      title: "シフトを見る・シフト希望を出す",
      href: "/manual/staff/12.mp4",
      poster: "/manual/staff/12.jpg",
      durationSec: 56,
      width: 390,
      height: 780,
    },
    {
      audience: "staff",
      title: "研修アンケートに答える",
      href: "/manual/staff/13.mp4",
      poster: "/manual/staff/13.jpg",
      durationSec: 51,
      width: 390,
      height: 780,
    },
  ],
  voiceCredit: "VOICEVOX:冥鳴ひまり",
};
